=== Naptie/openmetro/schemas/v1/lines.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["$schema", "schema_version", "network_id", "generated_at", "source", "records"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "network_id": {
      "type": "string"
    },
    "generated_at": {
      "type": "string"
    },
    "source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "url",
          "version",
          "retrieved_at",
          "license",
          "license_url",
          "attribution"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "retrieved_at": {
            "type": "string"
          },
          "license": {
            "type": "string",
            "enum": ["unknown", "cc0", "cc-by", "cc-by-sa", "odbl", "custom"]
          },
          "license_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "attribution": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name",
          "names",
          "aliases",
          "short_name",
          "mode",
          "status",
          "loop",
          "source_ids"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "names": {
            "type": "object",
            "required": ["zh", "en"],
            "properties": {
              "zh": {
                "type": "string"
              },
              "en": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "aliases": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "color": {
            "type": "string"
          },
          "text_color": {
            "type": "string"
          },
          "short_name": {
            "type": "string"
          },
          "mode": {
            "type": "string",
            "enum": [
              "metro",
              "suburban_rail",
              "light_rail",
              "tram",
              "monorail",
              "airport_express",
              "other"
            ]
          },
          "status": {
            "type": "string",
            "enum": ["operating", "under_construction"]
          },
          "loop": {
            "type": "boolean"
          },
          "source_ids": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["source", "id"],
              "properties": {
                "source": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "geometry": {
            "type": "object",
            "required": ["crs", "points"],
            "properties": {
              "crs": {
                "type": "string",
                "enum": ["wgs84", "gcj02", "bd09", "schematic"]
              },
              "points": {
                "type": "array",
                "items": {
                  "anyOf": [
                    {
                      "type": "object",
                      "required": ["lon", "lat", "crs"],
                      "properties": {
                        "lon": {
                          "type": "number"
                        },
                        "lat": {
                          "type": "number"
                        },
                        "crs": {
                          "type": "string",
                          "enum": ["wgs84", "gcj02", "bd09", "schematic", "none"]
                        }
                      },
                      "additionalProperties": false
                    },
                    {
                      "type": "object",
                      "required": ["x", "y", "crs"],
                      "properties": {
                        "x": {
                          "type": "number"
                        },
                        "y": {
                          "type": "number"
                        },
                        "crs": {
                          "type": "string",
                          "enum": ["wgs84", "gcj02", "bd09", "schematic", "none"]
                        }
                      },
                      "additionalProperties": false
                    }
                  ]
                }
              }
            },
            "additionalProperties": false
          },
          "valid_from": {
            "type": "string"
          },
          "valid_to": {
            "type": "string"
          },
          "extras": {
            "type": "object",
            "required": [],
            "properties": {},
            "additionalProperties": {
              "$id": "/schemas/unknown",
              "title": "unknown"
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== Naptie/openmetro/data/cn-jinan/lines.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/lines.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-jinan",
  "generated_at": "2026-10-12T11:11:04.025Z",
  "source": [],
  "records": [
    {
      "id": "cn-jinan-line-1",
      "name": "1号线",
      "names": {
        "zh": "1号线",
        "en": "Line 1"
      },
      "aliases": [
        "轨道交通1号线"
      ],
      "color": "#d10195",
      "short_name": "1",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "1号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000071030"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000071031"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "D10195",
        "amap_name": "1号线",
        "baidu_vehicle_name": "地铁1号线",
        "fare_policy": "mileage",
        "service_note": "往工研院方向每周五、六、日延长运营（末班约+30分钟）"
      }
    },
    {
      "id": "cn-jinan-line-2",
      "name": "2号线",
      "names": {
        "zh": "2号线",
        "en": "Line 2"
      },
      "aliases": [
        "轨道交通2号线"
      ],
      "color": "#ffa500",
      "short_name": "2",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "2号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000073474"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000073475"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "FFA500",
        "amap_name": "2号线",
        "baidu_vehicle_name": "地铁2号线",
        "fare_policy": "mileage"
      }
    },
    {
      "id": "cn-jinan-line-3",
      "name": "3号线",
      "names": {
        "zh": "3号线",
        "en": "Line 3"
      },
      "aliases": [
        "轨道交通3号线"
      ],
      "color": "#2249a3",
      "short_name": "3",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "3号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000066599"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000066622"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "2249A3",
        "amap_name": "3号线",
        "baidu_vehicle_name": "地铁3号线",
        "fare_policy": "mileage"
      }
    },
    {
      "id": "cn-jinan-line-4",
      "name": "4号线",
      "names": {
        "zh": "4号线",
        "en": "Line 4"
      },
      "aliases": [
        "轨道交通4号线"
      ],
      "color": "#018237",
      "short_name": "4",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "4号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217582"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217584"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "018237",
        "amap_name": "4号线",
        "baidu_vehicle_name": "地铁4号线",
        "fare_policy": "mileage"
      }
    },
    {
      "id": "cn-jinan-line-6",
      "name": "6号线",
      "names": {
        "zh": "6号线",
        "en": "Line 6"
      },
      "aliases": [
        "轨道交通6号线"
      ],
      "color": "#02b6e3",
      "short_name": "6",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "6号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217623"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217624"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "02B6E3",
        "amap_name": "6号线",
        "baidu_vehicle_name": "地铁6号线",
        "fare_policy": "mileage"
      }
    },
    {
      "id": "cn-jinan-line-8",
      "name": "8号线",
      "names": {
        "zh": "8号线",
        "en": "Line 8"
      },
      "aliases": [
        "轨道交通8号线"
      ],
      "color": "#5a2b8d",
      "short_name": "8",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "8号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217676"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000217679"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "5A2B8D",
        "amap_name": "8号线",
        "baidu_vehicle_name": "地铁8号线",
        "fare_policy": "mileage",
        "through_run_with": "4/8",
        "service_note": "往清源大街方向每周五至周日延长运营（末班约+25分钟）"
      }
    },
    {
      "id": "cn-jinan-line-jy",
      "name": "济阳线",
      "names": {
        "zh": "济阳线",
        "en": "Jiyang Line"
      },
      "aliases": [
        "轨道交通济阳线"
      ],
      "color": "#98d1c0",
      "short_name": "JY",
      "mode": "suburban_rail",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "济阳线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000235482"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000235483"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "98D1C0",
        "amap_name": "济阳线",
        "baidu_vehicle_name": "地铁济阳线",
        "fare_policy": "flat2"
      }
    },
    {
      "id": "cn-jinan-line-yb",
      "name": "云巴线",
      "names": {
        "zh": "云巴线",
        "en": "SkyShuttle Line"
      },
      "aliases": [
        "云巴1号线"
      ],
      "color": "#3080b7",
      "short_name": "YB",
      "mode": "monorail",
      "status": "operating",
      "loop": true,
      "source_ids": [
        {
          "source": "amap-subway-3701",
          "id": "云巴1号线"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000235330"
        },
        {
          "source": "amap-subway-3701",
          "id": "900000235331"
        }
      ],
      "extras": {
        "names_source": "source",
        "amap_color": "3080B7",
        "amap_name": "云巴1号线",
        "baidu_vehicle_name": "云巴1号线",
        "fare_policy": "mileage"
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-suzhou/lines.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/lines.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-suzhou",
  "generated_at": "2026-10-12T11:17:29.444Z",
  "source": [],
  "records": [
    {
      "id": "cn-suzhou-line-1",
      "name": "1号线",
      "names": {
        "zh": "1号线",
        "en": "Line 1"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#78be20",
      "short_name": "1",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "1"
        }
      ],
      "extras": {
        "source_line_index": 2,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-10",
      "name": "10号线",
      "names": {
        "zh": "10号线",
        "en": "Line 10"
      },
      "aliases": [],
      "mode": "metro",
      "status": "under_construction",
      "loop": false,
      "short_name": "10",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "10"
        }
      ],
      "extras": {
        "source_line_index": 0,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-11",
      "name": "11号线",
      "names": {
        "zh": "11号线",
        "en": "Line 11"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#f1c6a7",
      "short_name": "11",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "11"
        }
      ],
      "extras": {
        "source_line_index": 9,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-2",
      "name": "2号线",
      "names": {
        "zh": "2号线",
        "en": "Line 2"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#ef3340",
      "short_name": "2",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "2"
        }
      ],
      "extras": {
        "source_line_index": 3,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-3",
      "name": "3号线",
      "names": {
        "zh": "3号线",
        "en": "Line 3"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#ff8200",
      "short_name": "3",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "3"
        }
      ],
      "extras": {
        "source_line_index": 4,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-4",
      "name": "4号线",
      "names": {
        "zh": "4号线",
        "en": "Line 4"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#0072ce",
      "short_name": "4",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "4"
        }
      ],
      "extras": {
        "source_line_index": 5,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-5",
      "name": "5号线",
      "names": {
        "zh": "5号线",
        "en": "Line 5"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#e93cac",
      "short_name": "5",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "5"
        }
      ],
      "extras": {
        "source_line_index": 6,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-6",
      "name": "6号线",
      "names": {
        "zh": "6号线",
        "en": "Line 6"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#41b6e6",
      "short_name": "6",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "6"
        }
      ],
      "extras": {
        "source_line_index": 7,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-7",
      "name": "7号线",
      "names": {
        "zh": "7号线",
        "en": "Line 7"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#a77bca",
      "short_name": "7",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "7"
        }
      ],
      "extras": {
        "source_line_index": 8,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-8",
      "name": "8号线",
      "names": {
        "zh": "8号线",
        "en": "Line 8"
      },
      "aliases": [],
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "color": "#a09200",
      "short_name": "8",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "8"
        }
      ],
      "extras": {
        "source_line_index": 1,
        "names_source": "source",
        "is_extension_corridor": false
      }
    },
    {
      "id": "cn-suzhou-line-hykf",
      "name": "6延线",
      "names": {
        "zh": "6延线",
        "en": "Line 6 Extension"
      },
      "aliases": [],
      "mode": "metro",
      "status": "under_construction",
      "loop": false,
      "short_name": "6延线",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "9"
        }
      ],
      "extras": {
        "source_line_index": 10,
        "names_source": "source",
        "parent_line_no": "6",
        "is_extension_corridor": true,
        "parent_line_id": "cn-suzhou-line-6",
        "extension_pattern_id": "cn-suzhou-line-6-pattern-ext-hykf",
        "connector_stop_id": "cn-suzhou-sangtiandao-6",
        "stops_owned": 0
      }
    },
    {
      "id": "cn-suzhou-line-hzb4",
      "name": "7延线",
      "names": {
        "zh": "7延线",
        "en": "Line 7 Extension"
      },
      "aliases": [],
      "mode": "metro",
      "status": "under_construction",
      "loop": false,
      "short_name": "7延线",
      "source_ids": [
        {
          "source": "sz-mtr-map-js",
          "id": "12"
        }
      ],
      "extras": {
        "source_line_index": 11,
        "names_source": "source",
        "parent_line_no": "7",
        "is_extension_corridor": true,
        "parent_line_id": "cn-suzhou-line-7",
        "extension_pattern_id": "cn-suzhou-line-7-pattern-ext-hzb4",
        "connector_stop_id": "cn-suzhou-changlou-7",
        "stops_owned": 0
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-changsha/lines.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/lines.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-changsha",
  "generated_at": "2026-10-23T13:01:40.311Z",
  "source": [],
  "records": [
    {
      "id": "cn-changsha-line-1",
      "name": "1号线",
      "names": {
        "zh": "1号线",
        "en": "Line 1"
      },
      "aliases": [],
      "color": "#cc0000",
      "short_name": "1",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "d28aa9109e1540f7ad4ee42e4cbdc613"
        },
        {
          "source": "amap-subway-4301",
          "id": "430100020925|430100020926"
        }
      ],
      "extras": {
        "official_line_id": "d28aa9109e1540f7ad4ee42e4cbdc613",
        "official_line_code": 1,
        "official_start_name": "金盆丘(铜官窑巴士站)",
        "official_end_name": "尚双塘",
        "station_count": 25,
        "amap_color": "CC0000",
        "baidu_name_hint": "轨道交通1号线"
      }
    },
    {
      "id": "cn-changsha-line-2",
      "name": "2号线",
      "names": {
        "zh": "2号线",
        "en": "Line 2"
      },
      "aliases": [],
      "color": "#52a8c9",
      "short_name": "2",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "e4563f4c920f44d2ac4f38e34586a0af"
        },
        {
          "source": "amap-subway-4301",
          "id": "430100020927|430100020928"
        }
      ],
      "extras": {
        "official_line_id": "e4563f4c920f44d2ac4f38e34586a0af",
        "official_line_code": 2,
        "official_start_name": "光达",
        "official_end_name": "梅溪湖西",
        "station_count": 23,
        "amap_color": "52A8C9",
        "baidu_name_hint": "轨道交通2号线"
      }
    },
    {
      "id": "cn-changsha-line-3",
      "name": "3号线",
      "names": {
        "zh": "3号线",
        "en": "Line 3"
      },
      "aliases": [],
      "color": "#86b81c",
      "short_name": "3",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "4f7c68735e254f5b9c1462ecb7f3142c"
        },
        {
          "source": "amap-subway-4301",
          "id": "900000065929|900000065956"
        }
      ],
      "extras": {
        "official_line_id": "4f7c68735e254f5b9c1462ecb7f3142c",
        "official_line_code": 3,
        "official_start_name": "长沙方向（广生）",
        "official_end_name": "湘潭方向（红桥/湘潭北站）",
        "station_count": 33,
        "amap_color": "86B81C",
        "baidu_name_hint": "轨道交通3号线"
      }
    },
    {
      "id": "cn-changsha-line-4",
      "name": "4号线",
      "names": {
        "zh": "4号线",
        "en": "Line 4"
      },
      "aliases": [],
      "color": "#d10195",
      "short_name": "4",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "d8ad45f4dfe34f01949ac946433daec5"
        },
        {
          "source": "amap-subway-4301",
          "id": "900000066167|900000066174"
        }
      ],
      "extras": {
        "official_line_id": "d8ad45f4dfe34f01949ac946433daec5",
        "official_line_code": 4,
        "official_start_name": "罐子岭",
        "official_end_name": "杜家坪",
        "station_count": 25,
        "amap_color": "D10195",
        "baidu_name_hint": "轨道交通4号线"
      }
    },
    {
      "id": "cn-changsha-line-5",
      "name": "5号线",
      "names": {
        "zh": "5号线",
        "en": "Line 5"
      },
      "aliases": [],
      "color": "#fcd600",
      "short_name": "5",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "98642f513cf14562ba83d96a2c2fde80"
        },
        {
          "source": "amap-subway-4301",
          "id": "900000066175|900000066200"
        }
      ],
      "extras": {
        "official_line_id": "98642f513cf14562ba83d96a2c2fde80",
        "official_line_code": 5,
        "official_start_name": "毛竹塘",
        "official_end_name": "水渡河",
        "station_count": 18,
        "amap_color": "FCD600",
        "baidu_name_hint": "轨道交通5号线"
      }
    },
    {
      "id": "cn-changsha-line-6",
      "name": "6号线",
      "names": {
        "zh": "6号线",
        "en": "Line 6"
      },
      "aliases": [],
      "color": "#0065b3",
      "short_name": "6",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "0ca28e42bfc548228d259f9a9a4e40b6"
        },
        {
          "source": "amap-subway-4301",
          "id": "900000075109|900000075110"
        }
      ],
      "extras": {
        "official_line_id": "0ca28e42bfc548228d259f9a9a4e40b6",
        "official_line_code": 6,
        "official_start_name": "谢家桥",
        "official_end_name": "黄花机场T1T2",
        "station_count": 34,
        "amap_color": "0065B3",
        "baidu_name_hint": "轨道交通6号线"
      }
    },
    {
      "id": "cn-changsha-line-s2",
      "name": "磁浮快线",
      "names": {
        "zh": "磁浮快线",
        "en": "S2"
      },
      "aliases": [],
      "color": "#eb81b9",
      "short_name": "S2",
      "mode": "light_rail",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "hncsmtr-creatorcms",
          "id": "efb09986c7d04e9a92abf57379d2d2cb"
        },
        {
          "source": "amap-subway-4301",
          "id": "900000057211|900000057212"
        }
      ],
      "extras": {
        "official_line_id": "efb09986c7d04e9a92abf57379d2d2cb",
        "official_line_code": 7,
        "official_start_name": "磁浮高铁站",
        "official_end_name": "磁浮机场站",
        "station_count": 3,
        "amap_color": "EB81B9",
        "baidu_name_hint": "磁浮快线"
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-taiyuan/lines.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/lines.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-taiyuan",
  "generated_at": "2026-10-22T14:05:06.664Z",
  "source": [],
  "records": [
    {
      "id": "cn-taiyuan-line-1",
      "name": "1号线",
      "names": {
        "zh": "1号线",
        "en": "Line 1"
      },
      "aliases": [
        "轨道交通1号线"
      ],
      "color": "#0065b3",
      "short_name": "1",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "tymetro-api",
          "id": "2"
        },
        {
          "source": "amap-subway-1401",
          "id": "900000151669"
        },
        {
          "source": "amap-subway-1401",
          "id": "900000151670"
        }
      ],
      "extras": {
        "names_source": "source",
        "length_km": 28.737,
        "station_count": 24,
        "opened": "2025-02-22",
        "color_source": "amap-subway-1401",
        "amap_color": "0065B3",
        "amap_name": "1号线",
        "official_id": 2,
        "official_description": "1号线一期工程：西起西山矿务局，终至武宿机场，沿西矿街、迎泽大街、东中环、马练营路布设，全场28.737km，共设置车站24座，其中换乘站7座。",
        "line_map_image": "https://static.tymetro.ltd/tymetro/QqhIwnK9uzUMCI3jzYc839GKxhjoBy.jpg"
      }
    },
    {
      "id": "cn-taiyuan-line-2",
      "name": "2号线",
      "names": {
        "zh": "2号线",
        "en": "Line 2"
      },
      "aliases": [
        "轨道交通2号线"
      ],
      "color": "#cc0000",
      "short_name": "2",
      "mode": "metro",
      "status": "operating",
      "loop": false,
      "source_ids": [
        {
          "source": "tymetro-api",
          "id": "1"
        },
        {
          "source": "amap-subway-1401",
          "id": "900000056411"
        },
        {
          "source": "amap-subway-1401",
          "id": "900000056412"
        }
      ],
      "extras": {
        "names_source": "source",
        "length_km": 23.647,
        "station_count": 23,
        "opened": "2020-12-26",
        "color_source": "amap-subway-1401",
        "amap_color": "CC0000",
        "amap_name": "2号线",
        "official_id": 1,
        "official_description": "2号线一期工程：南起人民南路站，北至西涧河站，沿人民路、长治路、解放路地下敷设，全长23.647公里，共设车站23座，其中换乘站7座、车辆段1座。",
        "line_map_image": "https://static.tymetro.ltd/tymetro/zd4QDhaTm7XmfNDlxgQBZ1vt8ak0i2.png"
      }
    }
  ]
}
