=== Naptie/openmetro/schemas/v1/patterns.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["$schema", "schema_version", "network_id", "generated_at", "source", "records"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "network_id": {
      "type": "string"
    },
    "generated_at": {
      "type": "string"
    },
    "source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "url",
          "version",
          "retrieved_at",
          "license",
          "license_url",
          "attribution"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "retrieved_at": {
            "type": "string"
          },
          "license": {
            "type": "string",
            "enum": ["unknown", "cc0", "cc-by", "cc-by-sa", "odbl", "custom"]
          },
          "license_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "attribution": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "line_id",
          "stop_ids",
          "origin_stop_id",
          "terminal_stop_id",
          "is_primary",
          "source_ids"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "line_id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "names": {
            "type": "object",
            "required": ["zh", "en"],
            "properties": {
              "zh": {
                "type": "string"
              },
              "en": {
                "type": "string"
              }
            },
            "additionalProperties": false
          },
          "stop_ids": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "origin_stop_id": {
            "type": "string"
          },
          "terminal_stop_id": {
            "type": "string"
          },
          "is_primary": {
            "type": "boolean"
          },
          "junction_stop_id": {
            "type": "string"
          },
          "color": {
            "type": "string"
          },
          "geometry_reference_pattern_id": {
            "type": "string"
          },
          "source_ids": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["source", "id"],
              "properties": {
                "source": {
                  "type": "string"
                },
                "id": {
                  "type": "string"
                }
              },
              "additionalProperties": false
            }
          },
          "extras": {
            "type": "object",
            "required": [],
            "properties": {},
            "additionalProperties": {
              "$id": "/schemas/unknown",
              "title": "unknown"
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== Naptie/openmetro/data/cn-fuzhou/patterns.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/patterns.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-fuzhou",
  "generated_at": "2026-10-12T11:00:52.857Z",
  "source": [],
  "records": [
    {
      "id": "cn-fuzhou-pattern-1-primary",
      "line_id": "cn-fuzhou-line-1",
      "name": "象峰 → 三江口",
      "names": {
        "zh": "象峰→三江口",
        "en": "象峰 to 三江口"
      },
      "stop_ids": [
        "cn-fuzhou-xiangfeng-1",
        "cn-fuzhou-xiushan-1",
        "cn-fuzhou-luohanshan-1",
        "cn-fuzhou-fuzhou-railway-station-1",
        "cn-fuzhou-doumen-1",
        "cn-fuzhou-shudou-1",
        "cn-fuzhou-pingshan-1",
        "cn-fuzhou-dongjiekou-1",
        "cn-fuzhou-nanmendou-1",
        "cn-fuzhou-chating-1",
        "cn-fuzhou-dadao-1",
        "cn-fuzhou-shangteng-1",
        "cn-fuzhou-sanchajie-1",
        "cn-fuzhou-baihuting-1",
        "cn-fuzhou-huluzhen-1",
        "cn-fuzhou-huangshan-1",
        "cn-fuzhou-paixia-1",
        "cn-fuzhou-chengmen-1",
        "cn-fuzhou-sanjiaocheng-1",
        "cn-fuzhou-lulei-1",
        "cn-fuzhou-fuzhou-south-railway-station-1",
        "cn-fuzhou-anping-1",
        "cn-fuzhou-liangcuo-1",
        "cn-fuzhou-xiayang-1",
        "cn-fuzhou-sanjiangkou-1"
      ],
      "origin_stop_id": "cn-fuzhou-xiangfeng-1",
      "terminal_stop_id": "cn-fuzhou-sanjiangkou-1",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893281398853"
        }
      ],
      "extras": {
        "line_short_name": "1"
      }
    },
    {
      "id": "cn-fuzhou-pattern-2-primary",
      "line_id": "cn-fuzhou-line-2",
      "name": "苏洋 → 洋里",
      "names": {
        "zh": "苏洋→洋里",
        "en": "苏洋 to 洋里"
      },
      "stop_ids": [
        "cn-fuzhou-suyang-2",
        "cn-fuzhou-shadi-2",
        "cn-fuzhou-shangjie-2",
        "cn-fuzhou-jinyu-2",
        "cn-fuzhou-fuzhou-university-2",
        "cn-fuzhou-dongyu-fujian-normal-university-2",
        "cn-fuzhou-houting-2",
        "cn-fuzhou-juyuanzhou-2",
        "cn-fuzhou-hongwan-2",
        "cn-fuzhou-jinshan-2",
        "cn-fuzhou-jinxiang-2",
        "cn-fuzhou-xiangban-2",
        "cn-fuzhou-ninghua-2",
        "cn-fuzhou-xiyang-2",
        "cn-fuzhou-nanmendou-2",
        "cn-fuzhou-shuibu-2",
        "cn-fuzhou-ziyang-2",
        "cn-fuzhou-wuliting-2",
        "cn-fuzhou-qianyu-2",
        "cn-fuzhou-shangyang-2",
        "cn-fuzhou-gushan-2",
        "cn-fuzhou-yangli-2"
      ],
      "origin_stop_id": "cn-fuzhou-suyang-2",
      "terminal_stop_id": "cn-fuzhou-yangli-2",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893306720325"
        }
      ],
      "extras": {
        "line_short_name": "2"
      }
    },
    {
      "id": "cn-fuzhou-pattern-4-primary",
      "line_id": "cn-fuzhou-line-4",
      "name": "半洲 → 帝封江",
      "names": {
        "zh": "半洲→帝封江",
        "en": "半洲 to 帝封江"
      },
      "stop_ids": [
        "cn-fuzhou-banzhou-4",
        "cn-fuzhou-jianxin-4",
        "cn-fuzhou-hongtang-4",
        "cn-fuzhou-jinniushan-4",
        "cn-fuzhou-fenghuangchi-4",
        "cn-fuzhou-luzhuang-4",
        "cn-fuzhou-ximen-4",
        "cn-fuzhou-dongjiekou-4",
        "cn-fuzhou-provincial-hospital-4",
        "cn-fuzhou-dongmen-4",
        "cn-fuzhou-sanjiaochi-4",
        "cn-fuzhou-zhuyu-4",
        "cn-fuzhou-hengyu-4",
        "cn-fuzhou-houyu-4",
        "cn-fuzhou-qianyu-4",
        "cn-fuzhou-guangminggang-4",
        "cn-fuzhou-aofengzhou-4",
        "cn-fuzhou-huahai-park-4",
        "cn-fuzhou-exhibition-center-4",
        "cn-fuzhou-linpu-4",
        "cn-fuzhou-chengmen-4",
        "cn-fuzhou-luozhou-hot-spring-4",
        "cn-fuzhou-difengjiang-4"
      ],
      "origin_stop_id": "cn-fuzhou-banzhou-4",
      "terminal_stop_id": "cn-fuzhou-difengjiang-4",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893337657413"
        }
      ],
      "extras": {
        "line_short_name": "4"
      }
    },
    {
      "id": "cn-fuzhou-pattern-5-primary",
      "line_id": "cn-fuzhou-line-5",
      "name": "荆溪厚屿 → 福州火车南站",
      "names": {
        "zh": "荆溪厚屿→福州火车南站",
        "en": "荆溪厚屿 to 福州火车南站"
      },
      "stop_ids": [
        "cn-fuzhou-jingxi-houyu-5",
        "cn-fuzhou-agriculture-and-forestry-university-5",
        "cn-fuzhou-hongtang-5",
        "cn-fuzhou-zhenban-5",
        "cn-fuzhou-marong-5",
        "cn-fuzhou-jinshan-5",
        "cn-fuzhou-fenggangli-5",
        "cn-fuzhou-pushang-dadao-5",
        "cn-fuzhou-xiajing-5",
        "cn-fuzhou-dongling-5",
        "cn-fuzhou-taiyu-5",
        "cn-fuzhou-panyu-5",
        "cn-fuzhou-wushan-5",
        "cn-fuzhou-gaishan-zhulan-5",
        "cn-fuzhou-yixu-5",
        "cn-fuzhou-difengjiang-5",
        "cn-fuzhou-ancient-luozhou-town-5",
        "cn-fuzhou-qianjin-5",
        "cn-fuzhou-longjiang-5",
        "cn-fuzhou-fuzhou-south-railway-station-5"
      ],
      "origin_stop_id": "cn-fuzhou-jingxi-houyu-5",
      "terminal_stop_id": "cn-fuzhou-fuzhou-south-railway-station-5",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893359800389"
        }
      ],
      "extras": {
        "line_short_name": "5"
      }
    },
    {
      "id": "cn-fuzhou-pattern-6-primary",
      "line_id": "cn-fuzhou-line-6",
      "name": "潘墩 → 万寿",
      "names": {
        "zh": "潘墩→万寿",
        "en": "潘墩 to 万寿"
      },
      "stop_ids": [
        "cn-fuzhou-pandun-6",
        "cn-fuzhou-linpu-6",
        "cn-fuzhou-zhanglan-6",
        "cn-fuzhou-liangcuo-6",
        "cn-fuzhou-xiayang-6",
        "cn-fuzhou-yingqian-6",
        "cn-fuzhou-hangcheng-6",
        "cn-fuzhou-zhenghe-6",
        "cn-fuzhou-shiyang-6",
        "cn-fuzhou-wuhang-6",
        "cn-fuzhou-heshang-6",
        "cn-fuzhou-shajing-6",
        "cn-fuzhou-xiawu-6",
        "cn-fuzhou-wanshou-6"
      ],
      "origin_stop_id": "cn-fuzhou-pandun-6",
      "terminal_stop_id": "cn-fuzhou-wanshou-6",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893399121989"
        }
      ],
      "extras": {
        "line_short_name": "6"
      }
    },
    {
      "id": "cn-fuzhou-pattern-eg37cz-primary",
      "line_id": "cn-fuzhou-line-eg37cz",
      "name": "福州火车站 → 文岭",
      "names": {
        "zh": "福州火车站→文岭",
        "en": "福州火车站 to 文岭"
      },
      "stop_ids": [
        "cn-fuzhou-fuzhou-railway-station-滨海快线",
        "cn-fuzhou-dongmen-滨海快线",
        "cn-fuzhou-mindu-滨海快线",
        "cn-fuzhou-nangongyuan-滨海快线",
        "cn-fuzhou-sanchajie-滨海快线",
        "cn-fuzhou-difengjiang-滨海快线",
        "cn-fuzhou-xiangqian-滨海快线",
        "cn-fuzhou-shouzhan-滨海快线",
        "cn-fuzhou-dashuju-滨海快线",
        "cn-fuzhou-binhai-cbd-滨海快线",
        "cn-fuzhou-airport-滨海快线",
        "cn-fuzhou-wenling-滨海快线"
      ],
      "origin_stop_id": "cn-fuzhou-fuzhou-railway-station-滨海快线",
      "terminal_stop_id": "cn-fuzhou-wenling-滨海快线",
      "is_primary": true,
      "source_ids": [
        {
          "source": "fzmtr-services-schedule",
          "id": "749893426626629"
        }
      ],
      "extras": {
        "line_short_name": "滨海快线"
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-dongguan/patterns.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/patterns.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-dongguan",
  "generated_at": "2026-10-15T10:05:46.041Z",
  "source": [
    {
      "name": "dggdjt-service-times",
      "url": "https://www.dggdjt.com/info/17798.htmx",
      "version": "live",
      "retrieved_at": "2026-10-15T10:05:46.046Z",
      "license": "unknown",
      "license_url": null,
      "attribution": "东莞市轨道交通有限公司"
    },
    {
      "name": "amap-subway-4419",
      "url": "https://webapi.amap.com/subway/data/4419_drw_dongguan.json",
      "version": "live",
      "retrieved_at": "2026-10-15T10:05:46.046Z",
      "license": "unknown",
      "license_url": null,
      "attribution": "高德地图"
    }
  ],
  "records": [
    {
      "id": "cn-dongguan-pattern-1-primary",
      "line_id": "cn-dongguan-line-1",
      "name": "东莞西站 → 梅塘站",
      "names": {
        "zh": "东莞西站 → 梅塘站",
        "en": "Dongguanxi Railway Station to Meitang"
      },
      "stop_ids": [
        "cn-dongguan-bv09327050-1",
        "cn-dongguan-bv09327055-1",
        "cn-dongguan-bv09327058-1",
        "cn-dongguan-bv10844286-1",
        "cn-dongguan-bv09327052-1",
        "cn-dongguan-bv09327062-1",
        "cn-dongguan-bv09327057-1",
        "cn-dongguan-bv11144936-1",
        "cn-dongguan-bv09327056-1",
        "cn-dongguan-bv09327053-1",
        "cn-dongguan-bv11144934-1",
        "cn-dongguan-bv11338508-1",
        "cn-dongguan-bv11144928-1",
        "cn-dongguan-bv09327048-1",
        "cn-dongguan-bv11144929-1",
        "cn-dongguan-bv09327060-1",
        "cn-dongguan-bv09327059-1",
        "cn-dongguan-bv11144932-1",
        "cn-dongguan-bv09327054-1",
        "cn-dongguan-bv11144925-1",
        "cn-dongguan-bv09327061-1",
        "cn-dongguan-bv09327049-1",
        "cn-dongguan-bv09327051-1",
        "cn-dongguan-bv11284496-1",
        "cn-dongguan-bv09327063-1"
      ],
      "origin_stop_id": "cn-dongguan-bv09327050-1",
      "terminal_stop_id": "cn-dongguan-bv09327063-1",
      "is_primary": true,
      "source_ids": [
        {
          "source": "https://www.dggdjt.com/info/17798.htmx",
          "id": "1"
        }
      ]
    },
    {
      "id": "cn-dongguan-pattern-2-primary",
      "line_id": "cn-dongguan-line-2",
      "name": "东莞火车站 → 虎门火车站",
      "names": {
        "zh": "东莞火车站 → 虎门火车站",
        "en": "Dongguan Railway Station to Humen Railway Station"
      },
      "stop_ids": [
        "cn-dongguan-bv10525640-2",
        "cn-dongguan-bv10525641-2",
        "cn-dongguan-bv10525633-2",
        "cn-dongguan-bv10525632-2",
        "cn-dongguan-bv10525631-2",
        "cn-dongguan-bv10525642-2",
        "cn-dongguan-bv10525634-2",
        "cn-dongguan-bv09327056-2",
        "cn-dongguan-bv10525630-2",
        "cn-dongguan-bv10525636-2",
        "cn-dongguan-bv10525638-2",
        "cn-dongguan-bv10525643-2",
        "cn-dongguan-bv10525635-2",
        "cn-dongguan-bv10525639-2",
        "cn-dongguan-bv10525628-2"
      ],
      "origin_stop_id": "cn-dongguan-bv10525640-2",
      "terminal_stop_id": "cn-dongguan-bv10525628-2",
      "is_primary": true,
      "source_ids": [
        {
          "source": "https://www.dggdjt.com/info/17798.htmx",
          "id": "2"
        }
      ]
    }
  ]
}

=== Naptie/openmetro/data/cn-harbin/patterns.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/patterns.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-harbin",
  "generated_at": "2026-10-22T14:36:34.729Z",
  "source": [],
  "records": [
    {
      "id": "cn-harbin-pattern-1-primary",
      "line_id": "cn-harbin-line-1",
      "name": "新疆大街 → 哈尔滨东站",
      "names": {
        "zh": "新疆大街→哈尔滨东站",
        "en": "新疆大街 to 哈尔滨东站"
      },
      "stop_ids": [
        "cn-harbin-xinjiang-street-1",
        "cn-harbin-bohai-road-1",
        "cn-harbin-jingpo-road-1",
        "cn-harbin-wapenyao-1",
        "cn-harbin-tongjiang-road-1",
        "cn-harbin-harbin-south-railway-station-1",
        "cn-harbin-hada-1",
        "cn-harbin-the-second-affiliated-hospital-of-harbin-medical-university-1",
        "cn-harbin-heilongjiang-university-1",
        "cn-harbin-harbin-university-of-science-and-technology-1",
        "cn-harbin-xuefu-road-1",
        "cn-harbin-hexing-road-1",
        "cn-harbin-xidaqiao-1",
        "cn-harbin-harbin-institute-of-technology-1",
        "cn-harbin-harbin-railway-co-ltd-1",
        "cn-harbin-museum-of-heilongjiang-province-1",
        "cn-harbin-the-first-affiliated-hospital-of-harbin-medical-university-1",
        "cn-harbin-tobacco-manufacture-1",
        "cn-harbin-harbin-enginering-university-1",
        "cn-harbin-taipingqiao-1",
        "cn-harbin-jiaotongxueyuan-1",
        "cn-harbin-huashu-street-1",
        "cn-harbin-harbin-east-railway-station-1"
      ],
      "origin_stop_id": "cn-harbin-xinjiang-street-1",
      "terminal_stop_id": "cn-harbin-harbin-east-railway-station-1",
      "is_primary": true,
      "source_ids": [
        {
          "source": "amap-subway-2301",
          "id": "1号线"
        }
      ],
      "extras": {
        "line_short_name": "1"
      }
    },
    {
      "id": "cn-harbin-pattern-2-primary",
      "line_id": "cn-harbin-line-2",
      "name": "江北大学城 → 气象台",
      "names": {
        "zh": "江北大学城→气象台",
        "en": "江北大学城 to 气象台"
      },
      "stop_ids": [
        "cn-harbin-jiangbei-university-town-2",
        "cn-harbin-harbin-north-railway-station-2",
        "cn-harbin-dagengjia-2",
        "cn-harbin-longchuan-road-2",
        "cn-harbin-shimao-avenue-2",
        "cn-harbin-ice-and-snow-world-2",
        "cn-harbin-sun-island-2",
        "cn-harbin-peoples-square-2",
        "cn-harbin-zhongyang-street-2",
        "cn-harbin-shangzhi-street-2",
        "cn-harbin-harbin-railway-station-2",
        "cn-harbin-museum-of-heilongjiang-province-2",
        "cn-harbin-workers-cultural-palace-2",
        "cn-harbin-the-peoples-government-of-heilongjiang-province-2",
        "cn-harbin-provincial-hospital-2",
        "cn-harbin-zhujiang-road-2",
        "cn-harbin-nanzhi-road-2",
        "cn-harbin-northeast-agricultural-university-2",
        "cn-harbin-meteorological-observatory-2"
      ],
      "origin_stop_id": "cn-harbin-jiangbei-university-town-2",
      "terminal_stop_id": "cn-harbin-meteorological-observatory-2",
      "is_primary": true,
      "source_ids": [
        {
          "source": "amap-subway-2301",
          "id": "2号线"
        }
      ],
      "extras": {
        "line_short_name": "2"
      }
    },
    {
      "id": "cn-harbin-pattern-3-primary",
      "line_id": "cn-harbin-line-3",
      "name": "3号线环线",
      "names": {
        "zh": "3号线环线",
        "en": "Line 3 loop"
      },
      "stop_ids": [
        "cn-harbin-jinxiang-street-3",
        "cn-harbin-labor-park-3",
        "cn-harbin-xusheng-street-3",
        "cn-harbin-harbin-medical-university-cancer-hospital-3",
        "cn-harbin-zhengyi-road-3",
        "cn-harbin-the-second-affiliated-hospital-of-harbin-medical-university-3",
        "cn-harbin-haxi-street-3",
        "cn-harbin-kaishengyuan-plaza-3",
        "cn-harbin-harbin-west-railway-station-3",
        "cn-harbin-chengxiang-road-3",
        "cn-harbin-gongnong-street-3",
        "cn-harbin-qunli-hospital-the-first-affiliated-hospital-of-harbin-medical-university-3",
        "cn-harbin-no-5-qunli-avenue-3",
        "cn-harbin-sports-park-3",
        "cn-harbin-lilac-park-3",
        "cn-harbin-heshan-street-3",
        "cn-harbin-hesong-street-3",
        "cn-harbin-highway-bridge-3",
        "cn-harbin-shanghai-street-3",
        "cn-harbin-peoples-square-3",
        "cn-harbin-friendship-palace-hotel-3",
        "cn-harbin-zhaolin-park-3",
        "cn-harbin-beima-road-3",
        "cn-harbin-chinese-baroque-block-3",
        "cn-harbin-harbin-mosque-3",
        "cn-harbin-jingyu-park-3",
        "cn-harbin-taipingqiao-3",
        "cn-harbin-dayoufang-street-3",
        "cn-harbin-second-hospital-of-harbin-city-3",
        "cn-harbin-haihe-east-road-3",
        "cn-harbin-conference-and-exhibition-center-3",
        "cn-harbin-xiangjiang-road-3",
        "cn-harbin-zhujiang-road-3",
        "cn-harbin-gongbin-road-3",
        "cn-harbin-youfang-street-3",
        "cn-harbin-turbine-co-ltd-3"
      ],
      "origin_stop_id": "cn-harbin-jinxiang-street-3",
      "terminal_stop_id": "cn-harbin-turbine-co-ltd-3",
      "is_primary": true,
      "source_ids": [
        {
          "source": "amap-subway-2301",
          "id": "3号线"
        }
      ],
      "extras": {
        "line_short_name": "3",
        "loop": true
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-macau/patterns.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/patterns.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-macau",
  "generated_at": "2026-10-12T11:04:41.520Z",
  "source": [],
  "records": [
    {
      "id": "cn-macau-line-hengqin-pattern-lotus-to-hengqin",
      "line_id": "cn-macau-line-hengqin",
      "name": "橫琴線",
      "names": {
        "zh": "橫琴線",
        "en": "Hengqin Line"
      },
      "stop_ids": [
        "lotus-hengqin",
        "hengqin-hengqin"
      ],
      "origin_stop_id": "lotus-hengqin",
      "terminal_stop_id": "hengqin-hengqin",
      "is_primary": true,
      "color": "#BD273A",
      "source_ids": [
        {
          "source": "mlm-route",
          "id": "hengqin"
        }
      ],
      "extras": {
        "line_key": "hengqin",
        "direction": "down",
        "dest_name": "Hengqin"
      }
    },
    {
      "id": "cn-macau-line-spv-pattern-union-hospital-to-seac-pai-van",
      "line_id": "cn-macau-line-spv",
      "name": "石排灣線",
      "names": {
        "zh": "石排灣線",
        "en": "Seac Pai Van Line"
      },
      "stop_ids": [
        "union-hospital-spv",
        "seac-pai-van-spv"
      ],
      "origin_stop_id": "union-hospital-spv",
      "terminal_stop_id": "seac-pai-van-spv",
      "is_primary": true,
      "color": "#8A66C3",
      "source_ids": [
        {
          "source": "mlm-route",
          "id": "spv"
        }
      ],
      "extras": {
        "line_key": "spv",
        "direction": "down",
        "dest_name": "Seac Pai Van"
      }
    },
    {
      "id": "cn-macau-line-taipa-pattern-barra-to-taipa-ferry-terminal",
      "line_id": "cn-macau-line-taipa",
      "name": "氹仔線",
      "names": {
        "zh": "氹仔線",
        "en": "Taipa Line"
      },
      "stop_ids": [
        "barra-taipa",
        "ocean-taipa",
        "jockey-club-taipa",
        "stadium-taipa",
        "pai-kok-taipa",
        "cotai-west-taipa",
        "lotus-taipa",
        "union-hospital-taipa",
        "east-asian-games-taipa",
        "cotai-east-taipa",
        "must-taipa",
        "airport-taipa",
        "taipa-ferry-terminal-taipa"
      ],
      "origin_stop_id": "barra-taipa",
      "terminal_stop_id": "taipa-ferry-terminal-taipa",
      "is_primary": true,
      "color": "#93D50A",
      "source_ids": [
        {
          "source": "mlm-route",
          "id": "taipa"
        }
      ],
      "extras": {
        "line_key": "taipa",
        "direction": "down",
        "dest_name": "Taipa Ferry Terminal"
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-taiyuan/patterns.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/patterns.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-taiyuan",
  "generated_at": "2026-10-22T14:05:06.665Z",
  "source": [],
  "records": [
    {
      "id": "cn-taiyuan-pattern-1-primary",
      "line_id": "cn-taiyuan-line-1",
      "name": "1号线全线",
      "names": {
        "zh": "1号线全线",
        "en": "Line 1 full line"
      },
      "stop_ids": [
        "cn-taiyuan-he-longwan-1",
        "cn-taiyuan-ximing-lu-1",
        "cn-taiyuan-xike-zhan-1",
        "cn-taiyuan-jinyang-lu-1",
        "cn-taiyuan-yanjiagou-xiaojingyu-lu-1",
        "cn-taiyuan-xiayuan-1",
        "cn-taiyuan-taiyuan-ligong-daxue-1",
        "cn-taiyuan-taoyuan-lu-1",
        "cn-taiyuan-dananmen-1",
        "cn-taiyuan-liunan-1",
        "cn-taiyuan-wuyi-guangchang-1",
        "cn-taiyuan-taiyuan-zhanxi-guangchang-1",
        "cn-taiyuan-taiyuan-zhandong-guangchang-1",
        "cn-taiyuan-haojiagou-1",
        "cn-taiyuan-chaoyang-jie-1",
        "cn-taiyuan-shuangta-1",
        "cn-taiyuan-nanshifang-jie-1",
        "cn-taiyuan-changfeng-dongjie-1",
        "cn-taiyuan-xuefu-dongjie-1",
        "cn-taiyuan-xutan-dongjie-1",
        "cn-taiyuan-taiyuan-nanzhan-1",
        "cn-taiyuan-beiying-1",
        "cn-taiyuan-huangling-1",
        "cn-taiyuan-wusu-1-hao-2-hao-hangzhanlou-1"
      ],
      "origin_stop_id": "cn-taiyuan-he-longwan-1",
      "terminal_stop_id": "cn-taiyuan-wusu-1-hao-2-hao-hangzhanlou-1",
      "is_primary": true,
      "color": "#0065b3",
      "source_ids": [
        {
          "source": "tymetro-api",
          "id": "2"
        }
      ],
      "extras": {
        "line_short_name": "1"
      }
    },
    {
      "id": "cn-taiyuan-pattern-2-primary",
      "line_id": "cn-taiyuan-line-2",
      "name": "2号线全线",
      "names": {
        "zh": "2号线全线",
        "en": "Line 2 full line"
      },
      "stop_ids": [
        "cn-taiyuan-xiqiao-2",
        "cn-taiyuan-huazhang-xijie-2",
        "cn-taiyuan-tongda-jie-2",
        "cn-taiyuan-kangning-jie-2",
        "cn-taiyuan-dianzi-xijie-2",
        "cn-taiyuan-jiajie-2",
        "cn-taiyuan-longcheng-gongyuan-2",
        "cn-taiyuan-longxing-jie-2",
        "cn-taiyuan-jinyang-jie-2",
        "cn-taiyuan-nanzhonghuan-2",
        "cn-taiyuan-xuefu-jie-2",
        "cn-taiyuan-changfeng-jie-2",
        "cn-taiyuan-wangcun-nanjie-2",
        "cn-taiyuan-nanneihuan-2",
        "cn-taiyuan-tiyuguan-2",
        "cn-taiyuan-dananmen-2",
        "cn-taiyuan-kaihuasi-jie-2",
        "cn-taiyuan-fuxi-jie-2",
        "cn-taiyuan-jihuying-2",
        "cn-taiyuan-dabeimen-2",
        "cn-taiyuan-shenglijie-2",
        "cn-taiyuan-jianhe-2",
        "cn-taiyuan-jiancaoping-2"
      ],
      "origin_stop_id": "cn-taiyuan-xiqiao-2",
      "terminal_stop_id": "cn-taiyuan-jiancaoping-2",
      "is_primary": true,
      "color": "#cc0000",
      "source_ids": [
        {
          "source": "tymetro-api",
          "id": "1"
        }
      ],
      "extras": {
        "line_short_name": "2"
      }
    }
  ]
}
