=== Naptie/openmetro/schemas/v1/stops.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["$schema", "schema_version", "network_id", "generated_at", "source", "records"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "network_id": {
      "type": "string"
    },
    "generated_at": {
      "type": "string"
    },
    "source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "url",
          "version",
          "retrieved_at",
          "license",
          "license_url",
          "attribution"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "retrieved_at": {
            "type": "string"
          },
          "license": {
            "type": "string",
            "enum": ["unknown", "cc0", "cc-by", "cc-by-sa", "odbl", "custom"]
          },
          "license_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "attribution": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["id", "station_id", "line_id", "sequence"],
        "properties": {
          "id": {
            "type": "string"
          },
          "station_id": {
            "type": "string"
          },
          "line_id": {
            "type": "string"
          },
          "sequence": {
            "type": "number"
          },
          "is_terminal": {
            "type": "boolean"
          },
          "location": {
            "type": "object",
            "required": ["lon", "lat", "crs"],
            "properties": {
              "lon": {
                "type": "number"
              },
              "lat": {
                "type": "number"
              },
              "crs": {
                "type": "string",
                "enum": ["wgs84", "gcj02", "bd09", "schematic", "none"]
              }
            },
            "additionalProperties": false
          },
          "schematic": {
            "type": "object",
            "required": ["x", "y", "crs"],
            "properties": {
              "x": {
                "type": "number"
              },
              "y": {
                "type": "number"
              },
              "crs": {
                "type": "string",
                "enum": ["wgs84", "gcj02", "bd09", "schematic", "none"]
              }
            },
            "additionalProperties": false
          },
          "source_id": {
            "type": "string"
          },
          "extras": {
            "type": "object",
            "required": [],
            "properties": {},
            "additionalProperties": {
              "$id": "/schemas/unknown",
              "title": "unknown"
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== Naptie/openmetro/data/cn-macau/stops.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/stops.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-macau",
  "generated_at": "2026-10-12T11:04:41.520Z",
  "source": [],
  "records": [
    {
      "id": "airport-taipa",
      "station_id": "airport",
      "line_id": "cn-macau-line-taipa",
      "sequence": 11,
      "is_terminal": false,
      "location": {
        "lon": 113.579661,
        "lat": 22.156449,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:11",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "barra-taipa",
      "station_id": "barra",
      "line_id": "cn-macau-line-taipa",
      "sequence": 0,
      "is_terminal": true,
      "location": {
        "lon": 113.534903,
        "lat": 22.180541,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:0",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "cotai-east-taipa",
      "station_id": "cotai-east",
      "line_id": "cn-macau-line-taipa",
      "sequence": 9,
      "is_terminal": false,
      "location": {
        "lon": 113.574142,
        "lat": 22.14529,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:9",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "cotai-west-taipa",
      "station_id": "cotai-west",
      "line_id": "cn-macau-line-taipa",
      "sequence": 5,
      "is_terminal": false,
      "location": {
        "lon": 113.56287,
        "lat": 22.142123,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:5",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "east-asian-games-taipa",
      "station_id": "east-asian-games",
      "line_id": "cn-macau-line-taipa",
      "sequence": 8,
      "is_terminal": false,
      "location": {
        "lon": 113.57363,
        "lat": 22.139456,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:8",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "hengqin-hengqin",
      "station_id": "hengqin",
      "line_id": "cn-macau-line-hengqin",
      "sequence": 1,
      "is_terminal": true,
      "location": {
        "lon": 113.550454,
        "lat": 22.136977,
        "crs": "gcj02"
      },
      "source_id": "mlm:hengqin:1",
      "extras": {
        "line_key": "hengqin"
      }
    },
    {
      "id": "jockey-club-taipa",
      "station_id": "jockey-club",
      "line_id": "cn-macau-line-taipa",
      "sequence": 2,
      "is_terminal": false,
      "location": {
        "lon": 113.5523,
        "lat": 22.15419,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:2",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "lotus-hengqin",
      "station_id": "lotus",
      "line_id": "cn-macau-line-hengqin",
      "sequence": 0,
      "is_terminal": true,
      "location": {
        "lon": 113.56483,
        "lat": 22.136602,
        "crs": "gcj02"
      },
      "source_id": "mlm:hengqin:0",
      "extras": {
        "line_key": "hengqin"
      }
    },
    {
      "id": "lotus-taipa",
      "station_id": "lotus",
      "line_id": "cn-macau-line-taipa",
      "sequence": 6,
      "is_terminal": false,
      "location": {
        "lon": 113.56483,
        "lat": 22.136602,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:6",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "must-taipa",
      "station_id": "must",
      "line_id": "cn-macau-line-taipa",
      "sequence": 10,
      "is_terminal": false,
      "location": {
        "lon": 113.575625,
        "lat": 22.150112,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:10",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "ocean-taipa",
      "station_id": "ocean",
      "line_id": "cn-macau-line-taipa",
      "sequence": 1,
      "is_terminal": false,
      "location": {
        "lon": 113.546401,
        "lat": 22.154891,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:1",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "pai-kok-taipa",
      "station_id": "pai-kok",
      "line_id": "cn-macau-line-taipa",
      "sequence": 4,
      "is_terminal": false,
      "location": {
        "lon": 113.559544,
        "lat": 22.147957,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:4",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "seac-pai-van-spv",
      "station_id": "seac-pai-van",
      "line_id": "cn-macau-line-spv",
      "sequence": 1,
      "is_terminal": true,
      "location": {
        "lon": 113.566708,
        "lat": 22.128488,
        "crs": "gcj02"
      },
      "source_id": "mlm:spv:1",
      "extras": {
        "line_key": "spv"
      }
    },
    {
      "id": "stadium-taipa",
      "station_id": "stadium",
      "line_id": "cn-macau-line-taipa",
      "sequence": 3,
      "is_terminal": false,
      "location": {
        "lon": 113.556898,
        "lat": 22.151425,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:3",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "taipa-ferry-terminal-taipa",
      "station_id": "taipa-ferry-terminal",
      "line_id": "cn-macau-line-taipa",
      "sequence": 12,
      "is_terminal": true,
      "location": {
        "lon": 113.578876,
        "lat": 22.160074,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:12",
      "extras": {
        "line_key": "taipa"
      }
    },
    {
      "id": "union-hospital-spv",
      "station_id": "union-hospital",
      "line_id": "cn-macau-line-spv",
      "sequence": 0,
      "is_terminal": true,
      "location": {
        "lon": 113.568327,
        "lat": 22.135779,
        "crs": "gcj02"
      },
      "source_id": "mlm:spv:0",
      "extras": {
        "line_key": "spv"
      }
    },
    {
      "id": "union-hospital-taipa",
      "station_id": "union-hospital",
      "line_id": "cn-macau-line-taipa",
      "sequence": 7,
      "is_terminal": false,
      "location": {
        "lon": 113.568327,
        "lat": 22.135779,
        "crs": "gcj02"
      },
      "source_id": "mlm:taipa:7",
      "extras": {
        "line_key": "taipa"
      }
    }
  ]
}

=== Naptie/openmetro/data/cn-urumqi/stops.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/stops.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-urumqi",
  "generated_at": "2026-10-12T09:03:47.197Z",
  "source": [],
  "records": [
    {
      "id": "cn-urumqi-balou-1",
      "station_id": "cn-urumqi-balou",
      "line_id": "cn-urumqi-line-1",
      "sequence": 11,
      "is_terminal": false,
      "source_id": "八楼",
      "schematic": {
        "x": 1147,
        "y": 1189,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 11
      }
    },
    {
      "id": "cn-urumqi-beimen-1",
      "station_id": "cn-urumqi-beimen",
      "line_id": "cn-urumqi-line-1",
      "sequence": 16,
      "is_terminal": false,
      "source_id": "北门",
      "schematic": {
        "x": 1527,
        "y": 1591,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 16
      }
    },
    {
      "id": "cn-urumqi-botanical-garden-1",
      "station_id": "cn-urumqi-botanical-garden",
      "line_id": "cn-urumqi-line-1",
      "sequence": 5,
      "is_terminal": false,
      "source_id": "植物园",
      "schematic": {
        "x": 806,
        "y": 587,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 5
      }
    },
    {
      "id": "cn-urumqi-dadiwopu-1",
      "station_id": "cn-urumqi-dadiwopu",
      "line_id": "cn-urumqi-line-1",
      "sequence": 1,
      "is_terminal": false,
      "source_id": "大地窝堡",
      "schematic": {
        "x": 259,
        "y": 322,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 1
      }
    },
    {
      "id": "cn-urumqi-erdaoqiao-1",
      "station_id": "cn-urumqi-erdaoqiao",
      "line_id": "cn-urumqi-line-1",
      "sequence": 18,
      "is_terminal": false,
      "source_id": "二道桥",
      "schematic": {
        "x": 1527,
        "y": 1798,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 18
      }
    },
    {
      "id": "cn-urumqi-international-airport-1",
      "station_id": "cn-urumqi-international-airport",
      "line_id": "cn-urumqi-line-1",
      "sequence": 0,
      "is_terminal": true,
      "source_id": "国际机场",
      "schematic": {
        "x": 0,
        "y": 322,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 0
      }
    },
    {
      "id": "cn-urumqi-international-airport-apm",
      "station_id": "cn-urumqi-international-airport",
      "line_id": "cn-urumqi-line-apm",
      "sequence": 0,
      "is_terminal": true,
      "source_id": "国际机场",
      "schematic": {
        "x": 0,
        "y": 322,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "机场捷运",
        "amap_order": 0
      }
    },
    {
      "id": "cn-urumqi-nanhu-north-road-1",
      "station_id": "cn-urumqi-nanhu-north-road",
      "line_id": "cn-urumqi-line-1",
      "sequence": 13,
      "is_terminal": false,
      "source_id": "南湖北路",
      "schematic": {
        "x": 1527,
        "y": 1296,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 13
      }
    },
    {
      "id": "cn-urumqi-nanhu-square-1",
      "station_id": "cn-urumqi-nanhu-square",
      "line_id": "cn-urumqi-line-1",
      "sequence": 14,
      "is_terminal": false,
      "source_id": "南湖广场",
      "schematic": {
        "x": 1527,
        "y": 1387,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 14
      }
    },
    {
      "id": "cn-urumqi-nanmen-1",
      "station_id": "cn-urumqi-nanmen",
      "line_id": "cn-urumqi-line-1",
      "sequence": 17,
      "is_terminal": false,
      "source_id": "南门",
      "schematic": {
        "x": 1527,
        "y": 1695,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 17
      }
    },
    {
      "id": "cn-urumqi-north-international-airport-apm",
      "station_id": "cn-urumqi-north-international-airport",
      "line_id": "cn-urumqi-line-apm",
      "sequence": 1,
      "is_terminal": true,
      "source_id": "国际机场北",
      "schematic": {
        "x": 274,
        "y": 43,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "机场捷运",
        "amap_order": 1
      }
    },
    {
      "id": "cn-urumqi-sangong-1",
      "station_id": "cn-urumqi-sangong",
      "line_id": "cn-urumqi-line-1",
      "sequence": 3,
      "is_terminal": false,
      "source_id": "三工",
      "schematic": {
        "x": 734,
        "y": 381,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 3
      }
    },
    {
      "id": "cn-urumqi-santunbei-1",
      "station_id": "cn-urumqi-santunbei",
      "line_id": "cn-urumqi-line-1",
      "sequence": 20,
      "is_terminal": true,
      "source_id": "三屯碑",
      "schematic": {
        "x": 1527,
        "y": 2000,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 20
      }
    },
    {
      "id": "cn-urumqi-sports-center-1",
      "station_id": "cn-urumqi-sports-center",
      "line_id": "cn-urumqi-line-1",
      "sequence": 6,
      "is_terminal": false,
      "source_id": "体育中心",
      "schematic": {
        "x": 842,
        "y": 691,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 6
      }
    },
    {
      "id": "cn-urumqi-tieluju-1",
      "station_id": "cn-urumqi-tieluju",
      "line_id": "cn-urumqi-line-1",
      "sequence": 7,
      "is_terminal": false,
      "source_id": "铁路局",
      "schematic": {
        "x": 879,
        "y": 795,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 7
      }
    },
    {
      "id": "cn-urumqi-wangjialiang-1",
      "station_id": "cn-urumqi-wangjialiang",
      "line_id": "cn-urumqi-line-1",
      "sequence": 12,
      "is_terminal": false,
      "source_id": "王家梁",
      "schematic": {
        "x": 1369,
        "y": 1189,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 12
      }
    },
    {
      "id": "cn-urumqi-xiaoxigou-1",
      "station_id": "cn-urumqi-xiaoxigou",
      "line_id": "cn-urumqi-line-1",
      "sequence": 8,
      "is_terminal": false,
      "source_id": "小西沟",
      "schematic": {
        "x": 915,
        "y": 899,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 8
      }
    },
    {
      "id": "cn-urumqi-xinjiang-library-1",
      "station_id": "cn-urumqi-xinjiang-library",
      "line_id": "cn-urumqi-line-1",
      "sequence": 10,
      "is_terminal": false,
      "source_id": "新疆图书馆",
      "schematic": {
        "x": 988,
        "y": 1108,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 10
      }
    },
    {
      "id": "cn-urumqi-xinjiang-university-1",
      "station_id": "cn-urumqi-xinjiang-university",
      "line_id": "cn-urumqi-line-1",
      "sequence": 19,
      "is_terminal": false,
      "source_id": "新疆大学",
      "schematic": {
        "x": 1527,
        "y": 1895,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 19
      }
    },
    {
      "id": "cn-urumqi-xinxing-street-1",
      "station_id": "cn-urumqi-xinxing-street",
      "line_id": "cn-urumqi-line-1",
      "sequence": 15,
      "is_terminal": false,
      "source_id": "新兴街",
      "schematic": {
        "x": 1527,
        "y": 1491,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 15
      }
    },
    {
      "id": "cn-urumqi-xuanrendun-1",
      "station_id": "cn-urumqi-xuanrendun",
      "line_id": "cn-urumqi-line-1",
      "sequence": 2,
      "is_terminal": false,
      "source_id": "宣仁墩",
      "schematic": {
        "x": 550,
        "y": 322,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 2
      }
    },
    {
      "id": "cn-urumqi-yingbin-road-crossing-1",
      "station_id": "cn-urumqi-yingbin-road-crossing",
      "line_id": "cn-urumqi-line-1",
      "sequence": 4,
      "is_terminal": false,
      "source_id": "迎宾路口",
      "schematic": {
        "x": 770,
        "y": 483,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 4
      }
    },
    {
      "id": "cn-urumqi-zhongyinggong-1",
      "station_id": "cn-urumqi-zhongyinggong",
      "line_id": "cn-urumqi-line-1",
      "sequence": 9,
      "is_terminal": false,
      "source_id": "中营工",
      "schematic": {
        "x": 951,
        "y": 1004,
        "crs": "schematic"
      },
      "extras": {
        "line_short_name": "1",
        "amap_order": 9
      }
    }
  ]
}
