=== Naptie/openmetro/schemas/v1/timetables.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["$schema", "schema_version", "network_id", "generated_at", "source", "records"],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "schema_version": {
      "type": "string"
    },
    "network_id": {
      "type": "string"
    },
    "generated_at": {
      "type": "string"
    },
    "source": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "name",
          "url",
          "version",
          "retrieved_at",
          "license",
          "license_url",
          "attribution"
        ],
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": "string"
          },
          "version": {
            "type": "string"
          },
          "retrieved_at": {
            "type": "string"
          },
          "license": {
            "type": "string",
            "enum": ["unknown", "cc0", "cc-by", "cc-by-sa", "odbl", "custom"]
          },
          "license_url": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "type": "null"
              }
            ]
          },
          "attribution": {
            "type": "string"
          },
          "notes": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "records": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "station_id",
          "stop_id",
          "line_id",
          "pattern_id",
          "first_train",
          "last_train"
        ],
        "properties": {
          "id": {
            "type": "string"
          },
          "station_id": {
            "type": "string"
          },
          "stop_id": {
            "type": "string"
          },
          "line_id": {
            "type": "string"
          },
          "station_code": {
            "type": "string"
          },
          "source_id": {
            "type": "string"
          },
          "destination_stop_id": {
            "type": "string"
          },
          "origin_stop_id": {
            "type": "string"
          },
          "pattern_id": {
            "type": "string"
          },
          "direction_type": {
            "type": "string",
            "enum": ["linear", "loop_inner", "loop_outer"]
          },
          "direction_label": {
            "type": "string"
          },
          "first_train": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "last_train": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "first_train_desc": {
            "type": "string"
          },
          "last_train_desc": {
            "type": "string"
          },
          "is_arrival": {
            "type": "boolean"
          },
          "service": {
            "type": "string"
          },
          "valid_from": {
            "type": "string"
          },
          "valid_to": {
            "type": "string"
          },
          "extras": {
            "type": "object",
            "required": [],
            "properties": {},
            "additionalProperties": {
              "$id": "/schemas/unknown",
              "title": "unknown"
            }
          }
        },
        "additionalProperties": false
      }
    }
  },
  "additionalProperties": false
}

=== Naptie/openmetro/data/cn-hohhot/timetables.json
{
  "$schema": "https://raw.githubusercontent.com/Naptie/openmetro/main/schemas/v1/timetables.schema.json",
  "schema_version": "1.0",
  "network_id": "cn-hohhot",
  "generated_at": "2026-10-22T14:54:59.647Z",
  "source": [],
  "records": [
    {
      "id": "cn-hohhot-tt-cn-hohhot-aershan-road-2-up",
      "station_id": "cn-hohhot-aershan-road",
      "stop_id": "cn-hohhot-aershan-road-2",
      "line_id": "cn-hohhot-line-2",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-tali-east-road-2",
      "origin_stop_id": "cn-hohhot-aershan-road-2",
      "pattern_id": "cn-hohhot-pattern-2-primary",
      "direction_type": "linear",
      "direction_label": "往塔利东路方向",
      "first_train": [
        "06:00"
      ],
      "last_train": [
        "22:04"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "2",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-affiliated-hospital-1-down",
      "station_id": "cn-hohhot-affiliated-hospital",
      "stop_id": "cn-hohhot-affiliated-hospital-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-bayan-airport-1",
      "origin_stop_id": "cn-hohhot-yili-health-valley-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往坝堰(机场)(国内航站楼)方向",
      "first_train": [
        "06:15"
      ],
      "last_train": [
        "22:24"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-affiliated-hospital-1-up",
      "station_id": "cn-hohhot-affiliated-hospital",
      "stop_id": "cn-hohhot-affiliated-hospital-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-yili-health-valley-1",
      "origin_stop_id": "cn-hohhot-bayan-airport-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往伊利健康谷方向",
      "first_train": [
        "06:27"
      ],
      "last_train": [
        "22:30"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-arts-college-1-down",
      "station_id": "cn-hohhot-arts-college",
      "stop_id": "cn-hohhot-arts-college-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-bayan-airport-1",
      "origin_stop_id": "cn-hohhot-yili-health-valley-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往坝堰(机场)(国内航站楼)方向",
      "first_train": [
        "06:22"
      ],
      "last_train": [
        "22:33"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-arts-college-1-up",
      "station_id": "cn-hohhot-arts-college",
      "stop_id": "cn-hohhot-arts-college-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-yili-health-valley-1",
      "origin_stop_id": "cn-hohhot-bayan-airport-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往伊利健康谷方向",
      "first_train": [
        "06:19"
      ],
      "last_train": [
        "22:21"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-baihe-road-2-down",
      "station_id": "cn-hohhot-baihe-road",
      "stop_id": "cn-hohhot-baihe-road-2",
      "line_id": "cn-hohhot-line-2",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-aershan-road-2",
      "origin_stop_id": "cn-hohhot-tali-east-road-2",
      "pattern_id": "cn-hohhot-pattern-2-primary",
      "direction_type": "linear",
      "direction_label": "往阿尔山路方向",
      "first_train": [
        "06:03"
      ],
      "last_train": [
        "22:03"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "2",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-baihe-road-2-up",
      "station_id": "cn-hohhot-baihe-road",
      "stop_id": "cn-hohhot-baihe-road-2",
      "line_id": "cn-hohhot-line-2",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-tali-east-road-2",
      "origin_stop_id": "cn-hohhot-aershan-road-2",
      "pattern_id": "cn-hohhot-pattern-2-primary",
      "direction_type": "linear",
      "direction_label": "往塔利东路方向",
      "first_train": [
        "06:44"
      ],
      "last_train": [
        "22:50"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "2",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-baita-west-1-down",
      "station_id": "cn-hohhot-baita-west",
      "stop_id": "cn-hohhot-baita-west-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-bayan-airport-1",
      "origin_stop_id": "cn-hohhot-yili-health-valley-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往坝堰(机场)(国内航站楼)方向",
      "first_train": [
        "06:40"
      ],
      "last_train": [
        "22:51"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-baita-west-1-up",
      "station_id": "cn-hohhot-baita-west",
      "stop_id": "cn-hohhot-baita-west-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-yili-health-valley-1",
      "origin_stop_id": "cn-hohhot-bayan-airport-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往伊利健康谷方向",
      "first_train": [
        "06:02"
      ],
      "last_train": [
        "22:03"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-bayan-airport-1-up",
      "station_id": "cn-hohhot-bayan-airport",
      "stop_id": "cn-hohhot-bayan-airport-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-yili-health-valley-1",
      "origin_stop_id": "cn-hohhot-bayan-airport-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往伊利健康谷方向",
      "first_train": [
        "06:00"
      ],
      "last_train": [
        "22:01"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-beishan-park-2-down",
      "station_id": "cn-hohhot-beishan-park",
      "stop_id": "cn-hohhot-beishan-park-2",
      "line_id": "cn-hohhot-line-2",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-aershan-road-2",
      "origin_stop_id": "cn-hohhot-tali-east-road-2",
      "pattern_id": "cn-hohhot-pattern-2-primary",
      "direction_type": "linear",
      "direction_label": "往阿尔山路方向",
      "first_train": [
        "06:05"
      ],
      "last_train": [
        "22:05"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "2",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-beishan-park-2-up",
      "station_id": "cn-hohhot-beishan-park",
      "stop_id": "cn-hohhot-beishan-park-2",
      "line_id": "cn-hohhot-line-2",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-tali-east-road-2",
      "origin_stop_id": "cn-hohhot-aershan-road-2",
      "pattern_id": "cn-hohhot-pattern-2-primary",
      "direction_type": "linear",
      "direction_label": "往塔利东路方向",
      "first_train": [
        "06:42"
      ],
      "last_train": [
        "22:48"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "2",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-city-government-1-down",
      "station_id": "cn-hohhot-city-government",
      "stop_id": "cn-hohhot-city-government-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-bayan-airport-1",
      "origin_stop_id": "cn-hohhot-yili-health-valley-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往坝堰(机场)(国内航站楼)方向",
      "first_train": [
        "06:30"
      ],
      "last_train": [
        "22:41"
      ],
      "service": "all_days",
      "extras": {
        "line_short_name": "1",
        "calendar": "all_days"
      }
    },
    {
      "id": "cn-hohhot-tt-cn-hohhot-city-government-1-up",
      "station_id": "cn-hohhot-city-government",
      "stop_id": "cn-hohhot-city-government-1",
      "line_id": "cn-hohhot-line-1",
      "source_id": "baidu-direction-v2-transit",
      "destination_stop_id": "cn-hohhot-yili-health-valley-1",
      "origin_stop_id": "cn-hohhot-bayan-airport-1",
      "pattern_id": "cn-hohhot-pattern-1-primary",
      "direction_type": "linear",
      "direction_label": "往伊利健康谷方向",
      "first_train": [
        "06:11"
      ],
      "last_train": [
        "22:12"
      ],
      "service": "all_days",
      "extras": {
